# Generated by Django 3.1.2 on 2020-10-27 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('shipmentId', models.IntegerField(primary_key=True, serialize=False)),
                ('shipmentDate', models.DateTimeField()),
                ('shipmentReference', models.CharField(max_length=50)),
                ('transportId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopCredentials',
            fields=[
                ('shopName', models.CharField(default='', max_length=50, unique=True)),
                ('shopId', models.AutoField(primary_key=True, serialize=False)),
                ('clientId', models.CharField(default='', max_length=50, unique=True)),
                ('clientSecret', models.CharField(default='', max_length=100)),
                ('clientToken', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportId', models.IntegerField()),
                ('transporterCode', models.CharField(default='', max_length=50)),
                ('trackAndTrace', models.CharField(default='', max_length=50)),
                ('shippingLabelId', models.IntegerField()),
                ('shippingLabelCode', models.CharField(default='', max_length=50)),
                ('shipmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bol_client.shipments')),
            ],
        ),
        migrations.CreateModel(
            name='tokenRequestLog',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.DateTimeField(auto_now=True)),
                ('shopId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bol_client.shopcredentials')),
            ],
        ),
        migrations.CreateModel(
            name='shopRequestLog',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.DateTimeField(auto_now=True)),
                ('shopId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bol_client.shopcredentials')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderItemId', models.IntegerField()),
                ('orderId', models.IntegerField()),
                ('orderDate', models.DateTimeField()),
                ('latestDeliveryDate', models.DateTimeField()),
                ('ean', models.IntegerField()),
                ('title', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField()),
                ('offerprice', models.FloatField()),
                ('offerCondition', models.CharField(default='', max_length=50)),
                ('offerReference', models.CharField(default='', max_length=50)),
                ('fulfilmentMethod', models.CharField(default='', max_length=50)),
                ('shipmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bol_client.shipments')),
            ],
        ),
        migrations.AddField(
            model_name='shipments',
            name='shopId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bol_client.shopcredentials'),
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickUpPointName', models.CharField(default='', max_length=50)),
                ('salutationCode', models.CharField(default='', max_length=50)),
                ('firstName', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('streetName', models.CharField(default='', max_length=50)),
                ('houseNumber', models.CharField(default='', max_length=50)),
                ('houseNumberExtended', models.CharField(default='', max_length=50)),
                ('addressSupplement', models.CharField(default='', max_length=50)),
                ('extraAddressInformation', models.CharField(default='', max_length=50)),
                ('zipCode', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('countryCode', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('company', models.CharField(default='', max_length=50)),
                ('vatNumber', models.CharField(default='', max_length=50)),
                ('chamberOfCommerceNumber', models.CharField(default='', max_length=50)),
                ('orderReference', models.CharField(default='', max_length=50)),
                ('deliveryPhoneNumber', models.CharField(default='', max_length=50)),
                ('shipmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bol_client.shipments')),
            ],
        ),
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickUpPointName', models.CharField(default='', max_length=50)),
                ('salutationCode', models.CharField(default='', max_length=50)),
                ('firstName', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('streetName', models.CharField(default='', max_length=50)),
                ('houseNumber', models.CharField(default='', max_length=50)),
                ('houseNumberExtended', models.CharField(default='', max_length=50)),
                ('addressSupplement', models.CharField(default='', max_length=50)),
                ('extraAddressInformation', models.CharField(default='', max_length=50)),
                ('zipCode', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('countryCode', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('company', models.CharField(default='', max_length=50)),
                ('vatNumber', models.CharField(default='', max_length=50)),
                ('chamberOfCommerceNumber', models.CharField(default='', max_length=50)),
                ('orderReference', models.CharField(default='', max_length=50)),
                ('deliveryPhoneNumber', models.CharField(default='', max_length=50)),
                ('shipmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bol_client.shipments')),
            ],
        ),
    ]
